### ISSUE TITLE
Journeymap waypoint beacon does not match physical coordinates of waypoint itself

### ISSUE THREAD

**Issue by risric** [ClaudiusMinimus/Create_Potato#4]
When attempting to navigate to a waypoint the beacon is 100-300 meters off usually to the Southwest. and the beacon itself moves closer to you as you walk towards it. (I the speed the beacon moves is the same as your walk speed, so you meet the beacon at the at the halfway point if you started at the waypoint coordinates.)

**Comment by ClaudiusMinimus** [comment]
I will report this to the makers of Journeymap. Thank you for bringing this to my attention.

**Comment by mysticdrew** [comment]
So.. I looked into the issue a bit, well I just loaded the pack. There is another mod conflicting here and I am not sure which mod it is. 

So, first we need to find out which mod it is and either I can create a work around or we can talk to the other mod dev to address the issue. But first we need to find the mod.

To do that, remove half the mods. Create a new world, see if the issue persists. If not, the mod causing it is in the half your removed, if it is, then it is in your current half. 

Then do it again, use the half that it is still broken and cut that in half again, repeat until the culprit is found.  Once the offending mod is found, it will be pretty straight forward for me to fix on my end or work with the other mod dev.

**Comment by mysticdrew** [comment]
The mod causing the issue is Allomancy 4.2.1

**Comment by ClaudiusMinimus** [comment]
Thank you for finding the cause of this issue! How do I proceed from here?

**Comment by mysticdrew** [comment]
They are not cleaning up the buffers after RenderWorldLastEvent. I will see if I can get in contact with the dev.

**Comment by mysticdrew** [comment]
Their next release fixes the issue. It is not available yet. I built Allomancy 4.3.0 locally and it worked fine. 
https://github.com/legobmw99/Allomancy/issues/52

**Comment by ClaudiusMinimus** [comment]
Thank for looking into this!

**Comment by ClaudiusMinimus** [comment]
[legobmw99/Allomancy#52](https://github.com/legobmw99/Allomancy/issues/52) fixes this issue, wait for the 4.3.0 release
